<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 * @generated
 * @phutil-library-version 2
 */

phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' =>
  array(
    'BurndownApplication' => 'src/BurndownApplication.php',
    'BurndownController' => 'src/BurndownController.php',
    'BurndownData' => 'src/BurndownData.php',
    'BurndownDataDate' => 'src/BurndownDataDate.php',
    'SprintEndDateField' => 'src/SprintEndDateField.php',
    'SprintProjectCustomField' => 'src/SprintProjectCustomField.php',
    'SprintStartDateField' => 'src/SprintStartDateField.php',
    'SprintTaskStoryPointsField' => 'src/SprintTaskStoryPointsField.php',
  ),
  'function' =>
  array(
  ),
  'xmap' =>
  array(
    'BurndownApplication' => 'PhabricatorApplication',
    'BurndownController' => 'PhabricatorController',
    'SprintEndDateField' => 'SprintProjectCustomField',
    'SprintProjectCustomField' =>
    array(
      0 => 'PhabricatorProjectCustomField',
      1 => 'PhabricatorStandardCustomFieldInterface',
    ),
    'SprintStartDateField' => 'SprintProjectCustomField',
    'SprintTaskStoryPointsField' =>
    array(
      0 => 'ManiphestCustomField',
      1 => 'PhabricatorStandardCustomFieldInterface',
    ),
  ),
));
